// <auto-generated />
namespace Pipr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addWords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWords));
        
        string IMigrationMetadata.Id
        {
            get { return "201409301928540_addWords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
