// <auto-generated />
namespace Pipr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addShellCommands : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addShellCommands));
        
        string IMigrationMetadata.Id
        {
            get { return "201409182140185_addShellCommands"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
